### ISSUE TITLE
Refactoring border top class

### ISSUE THREAD

**Issue by shadeed** [kholoud840/NoonPost-repo#9]
I noticed the following CSS

```css
.c-media--topline {
    border-top: 1px solid #eee;
}
```

What if we replaced it with something like:

```css
.u-border-top {
    border-top: 1px solid #eee;
}
```

That way, we can use it on any different component. It doesn't need to be a media element.
